import { Metadata } from "next";
import styles from "app/page.module.css";

export const metadata: Metadata = {
    title: "Next Contacts",
    description: "Generated by Nataly",
};

export default function Contacts() {
    return (
        <div className={styles.description}>
            <div className={styles.center}>
                <h1>Contacts</h1>
            </div>
        </div>
    );
}
