import { Metadata } from "next";
import styles from "app/page.module.css";
import Link from "next/link";

async function getData() {
    const response = await fetch("https://jsonplaceholder.typicode.com/posts", {});
    if (!response.ok) throw new Error("Can't fetch posts");

    return response.json();
}

export const metadata: Metadata = {
    title: "Next Blog",
    description: "Generated by Nataly",
};

export default async function Blog() {
    const posts = await getData();
    console.log(posts);

    return (
        <div className={styles.description}>
            <div className={styles.center}>
                <h1>Blog</h1>
            </div>
            <ul style={{ listStyle: "none" }}>
                {posts.map((post: any) => (
                    <li key={post.id}>
                        <Link href={`blog/${post.id}`}>{post.title}</Link>
                    </li>
                ))}
            </ul>
        </div>
    );
}
