import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "./page.module.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next App",
    description: "Generated by Nataly",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ height: "100%" }}>
                <div className={styles.main}>
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
